/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include "stm32f4xx.h"
#include "fpu.h"
#include "uart.h"
#include "timebase.h"
#include "bsp.h"
#include "adc.h"
#include "circular_buffer.h"

#define GPIOAEN (1U << 0)
#define PIN5 (1U << 5)
#define LED_PIN PIN5

static bool btn_state;
static uint32_t sensor_value;

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
  /*Enable FPU*/
  fpu_enable();

  /*Initialize debug UART*/
  debug_uart_init();
  slave_dev_uart_init();

  /*Initialize timebase*/
  timebase_init();

  /*Initialize LED*/
  led_init();

  /*Initialize Push button*/
  button_init();

  /*Initialize ADC*/
  pa1_adc_init();

  circular_buffer_init();
  /*Start conversion*/
  // start_conversion();

  while (1)
  {

    // printf("Slave Dev UART...\n\r");

    buffer_send_string("Hello DEBUG\n\r", DEBUG_PORT);
    buffer_send_string("Hello SLAVE DEV\n\r", SLAVE_DEV_PORT);

    delay(1);
  }
}
